CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_BATTERY_REPORTING=y

# Принудительная генерация случайного нового MAC-адреса для обхода блокировок Windows
CONFIG_BT_PRIVACY=y
