# Переводим донгл в режим координатора сплит-системы
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Опрашивать и проксировать батарею с обеих радио-половинок в ПК
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Максимальное усиление радио-сигнала
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Разрешаем донглу помнить много пар ключей шифрования
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# КРИТИЧЕСКИЙ ФЛАГ: Принудительно разрешаем сопряжение со второй половинкой,
# даже если первая уже успешно подключилась к донглу!
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
